name: QA Docker CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t qa-test .

      - name: Run tests in Docker (parallel)
        run: |
          mkdir -p tmp/allure-results
          docker run --rm \
            -v "${{ github.workspace }}/tmp/allure-results:/usr/src/app/allure-results" \
            qa-test || true

  merge-and-upload:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      allure_found: ${{ steps.merge-allure.outputs.allure_found }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge Allure results
        id: merge-allure
        run: |
          mkdir -p tmp/allure-merged
          if [ -d tmp/allure-results ]; then
            find tmp/allure-results -mindepth 1 -maxdepth 1 -type d -exec cp -r {}/* tmp/allure-merged/ \;
          fi

          if [ "$(ls -A tmp/allure-merged)" ]; then
            echo "allure_found=true" >> $GITHUB_OUTPUT
          else
            echo "allure_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Allure Results Raw
        if: needs.merge-and-upload.outputs.allure_found == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: tmp/allure-merged

      - name: Generate Allure report
        if: needs.merge-and-upload.outputs.allure_found == 'true'
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: tmp/allure-merged
          allure_report: allure-report
