name: QA Docker CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v5

      # Build Docker image
      - name: Build Docker image
        run: docker build -t qa-test .

      # Run tests inside Docker (parallel via pytest-xdist)
      - name: Run tests in Docker
        run: |
          mkdir -p tmp/allure-results
          docker run --rm \
            -v "${{ github.workspace }}/tmp/allure-results:/usr/src/app/allure-results" \
            qa-test || true

      # Merge Allure results into a flat structure
      - name: Merge Allure results
        run: |
          mkdir -p tmp/allure-merged
          if [ -d tmp/allure-results ]; then
            # Copy all JSON files from worker subfolders to tmp/allure-merged
            find tmp/allure-results -mindepth 2 -name '*.json' -exec cp {} tmp/allure-merged/ \;
          fi

      # Upload Allure results (for GitHub artifact)
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: tmp/allure-merged

      # Generate Allure report
      - name: Generate Allure report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: tmp/allure-merged
          allure_report: allure-report
